# Floating window rules for waybar-weather-tui popup
windowrule = float on, match:tag floating-weather-tui
windowrule = center on, match:tag floating-weather-tui
windowrule = size 695 600, match:tag floating-weather-tui

windowrule = tag +floating-weather-tui, match:class custom.weather.tui
